ALTER TABLE chatbots
DROP COLUMN position,
DROP COLUMN bot_message_color,
DROP COLUMN user_message_color,
DROP COLUMN bot_message_text_color,
DROP COLUMN user_message_text_color,
DROP COLUMN chat_font_family,
DROP COLUMN chat_header_color,
DROP COLUMN chat_header_text_color,
DROP COLUMN bot_icon,
DROP COLUMN bot_display_name;
