BEGIN;

DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS analytics;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS data_sources;
DROP TABLE IF EXISTS chatbots;
DROP TABLE IF EXISTS users;

COMMIT;
