version: 2
run:
  timeout: 5m
  tests: false
  skip-dirs:
    - frontend
    - widget
linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosec
    - ineffassign
    - unused
    - misspell
linters-settings:
  govet:
    check-shadowing: true
    # - gocyclo
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
